### ISSUE TITLE
Using a gittracked folder

### ISSUE THREAD

**Issue by Webrow** [Berserk-Games/atom-tabletopsimulator-lua#111]
I am trying to send my gittracked folder to tts. But I only seem to be able to send my C:\Users\--\AppData\Local\Temp\TabletopSimulator to TTS. I want to edit files, make commits, while sending it to TTS inbetween, am I doing something wrong here?

**Comment by onelivesleft** [comment]
See this blog post on how to set up atom so you can use source control: http://blog.onelivesleft.com/2017/08/atom-tabletop-simulator-package.html
