### ISSUE TITLE
ctrl-shift-L conflicts with the Grammar Selector

### ISSUE THREAD

**Issue by PathosZero** [Berserk-Games/atom-tabletopsimulator-lua#117]
The ctrl-shift L function (Grammar Selector) is overridden by the Tabletop Simulator's "Get Lua Scripts from game" function. I use the Grammar Selector function constantly so this essentially breaks Atom for me.

**Comment by Benjamin-Dobell** [comment]
The key bindings are user configurable, so you may bind `tabletopsimulator-lua:getObjects` to a different key combination to avoid the issue:

![Screen Shot 2020-05-17 at 2 04 18 am](https://user-images.githubusercontent.com/482276/82124519-c616af80-97e2-11ea-91d5-f30770e79820.png)

**Comment by PathosZero** [comment]
Thanks!

Although it still seems like an odd choice that bindings for a plug in are overriding core functions of the editor.
