### ISSUE TITLE
Tabs open

### ISSUE THREAD

**Issue by Kijan** [Berserk-Games/atom-tabletopsimulator-lua#72]
i have installed atom and this plugin new because of new PC.
now i tryed to adjust the settings like it where before for me.
but when i load the scripts in Atom i got all scripts in tabs...
so i looked in the settings.... there is comminication.
"Only automatically open the Global script file"
I chose this...
now i got only the Global script no other scripts will be in the projects pane....
so the Project Pane is only the gloabel script in and when i send it to TTS the thing will be saved and loaded but i get the global script and the script i worked on but the project pane have also only these 2.
i am used to all scripts will be loaded in the project pane but only 1 or 2 are loaded in a tab

**Comment by onelivesleft** [comment]
Fixed in v10.6.2
