### ISSUE TITLE
onObjectSearchStart parameters the wrong way around.

### ISSUE THREAD

**Issue by Mr-Rockers** [Berserk-Games/atom-tabletopsimulator-lua#88]
Hello! o/

This is just to let you know that the plugin autocompletes onObjectSearchStart to
`onObjectSearchStart(player_color, object)`
However, the names of the variables should be the other way around
`onObjectSearchStart(object, player_color)`

I have yet to test this with onObjectSearchEnd, but it's just to let you know about this issue.

Many thanks!
-Lyes

**Comment by onelivesleft** [comment]
This may have been fixed ealier, but is definitely fixed in v12.4.0
