### ISSUE TITLE
ctrl-g conflicts with go-to-line shortcut

### ISSUE THREAD

**Issue by lockyer** [Berserk-Games/atom-tabletopsimulator-lua#99]
`ctrl-g` is a common key binding in many editors for going to a specific line in a text file. This is a shortcut I use a lot, and I suspect I'm not the only one. I'm currently working around this by creating my own `keymap.cson` file:
```
'atom-text-editor:not([mini])':
  'ctrl-g': 'go-to-line:toggle'
  'ctrl-r': 'tabletopsimulator-lua:gotoFunction'
```
However, I don't think this should be necessary.

`ctrl-r` might be a good option to override since the Tabletop Simulator lua plugin doesn't seem to have generic symbol finding support. Otherwise it also looks like `ctrl-shift-j` is also unused, but could be used as **J**ump to function/method. These are just some suggestions, I'm sure there are lots of other good alternatives I haven't thought of. 

I sympathize that finding good key combos that don't conflict is always a challenge!

![image](https://user-images.githubusercontent.com/830734/63228259-09e47600-c1cb-11e9-9d60-4d1194436137.png)

**Comment by onelivesleft** [comment]
The goto function call accepts a line number

**Comment by lockyer** [comment]
Oh! okay that's not so bad then! Still might be a good idea to make that a little more obvious by adding some help text like the built-in go-to-line has:

![image](https://user-images.githubusercontent.com/830734/63228549-09e67500-c1cf-11e9-8107-ccff6540db63.png)
